title: MUHAMMAD IKHSAN
logo: "/assets/images/Mask group (6).png?raw=true"
description: 
  <a href="https://www.linkedin.com/in/ikhsan-muhammad">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
