title: MUHAMMAD IKHSAN
logo: "/assets/images/Mask group (9).png?raw=true"
description: >
  #EDA #DataVisualization #DataCleaning #Data-Driven #DecisionMaking
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
